server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      routes:
      - id: getOrder
        uri: lb://CLOUD-PROVIDER-PAYMENT
        predicates:
        - Path=/gg/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
            key-resolver: "#{@ipKeyResolver}"
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 30000



eureka:
  instance:
    appname: cloud-gateway-service
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # defaultZone: http://localhost:7001/eureka/ 单机版
      defaultZone: http://eureka7001.com:7001/eureka/ #集群版
