server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7001.com #修改本地hosts文件，映射127.0.0.1 eureka7001.com
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #单机模式指定自己
      # defaultZone: http://eureka7002.com:7002/eureka/ 集群模式时使用7002

